eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8801/eureka/
server:
  port: 8807
spring:
  application:
    name: zuul
zuul:
  routes:
    api-a:
      path: /api-mcds/**
      serviceId: mcdsCore
    api-b:
      path: /api-order/**
      serviceId: orderCore
